USE master
GO
IF DB_ID('QLPK') IS NOT NULL
	DROP DATABASE QLPK
GO
CREATE DATABASE QLPK
GO
CREATE TABLE BENHNHAN
(
	IDBENHNHAN CHAR(10),
	HOTEN NVARCHAR(50),
	SODIENTHOAI CHAR(10),
	NGAYSINH DATE,
	GIOITINH NVARCHAR(5),
	DIACHI NVARCHAR(100) NOT NULL
	
	CONSTRAINT PK_BENHNHAN
	PRIMARY KEY(IDBENHNHAN),
	CONSTRAINT CK_BENHNHAN_PHAI
	CHECK (GIOITINH ='NAM' OR GIOITINH = N'NỮ')
)

CREATE TABLE 
asdfasdf
asdfas
fd
asdf